setTestName("Factorial")
print("factorial is :")
print(fact(5))
reportError("no errors :3")
leftClick(100,100)
executeJS("console.log('Hello from haskell and lua')")
takeAndSaveScreenshot("Aboba.png")